import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import ResponsiveNav from "../components/shared/Navbar/ResponsiveNav";
import Provider from "../components/shared/Hoc/Provider";
import Footer from "../components/Home/Footer/Footer";
import ScrollToTop from "../components/shared/Helper/ScrollToTop";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthProvider from "../context/AuthContext";
import { AuthModalProvider } from "../context/AuthModalContext";
import { Network } from 'lucide-react';

const App = () => {
  return (
    <Network />
  );
};

const font = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "JobNest",
  description: "Generated by create next app",
  icons: {
    icon: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="%23155e75"/><svg x="8" y="8" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="%23ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="16" y="16" width="6" height="6" rx="1"/><rect x="2" y="16" width="6" height="6" rx="1"/><rect x="9" y="2" width="6" height="6" rx="1"/><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"/><path d="M12 12V8"/></svg></svg>',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={`${font.className} antialiased`}>

        {/* BỌC TOÀN BỘ APP TRONG Google Provider */}
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}>

          {/* Bên trong là AuthProvider + UI */}
          <AuthProvider>
            <AuthModalProvider>
              <Provider>
                <ResponsiveNav />
                {children}
                <Footer />
                <ScrollToTop />
              </Provider>
            </AuthModalProvider>
          </AuthProvider>
        </GoogleOAuthProvider>

      </body>
    </html>
  );
}
