import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import Provider from "@/shared/components/Hoc/Provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthProvider from "@/features/auth/context/AuthContext";
import { AuthModalProvider } from "@/features/auth/context/AuthModalContext";
import AppChrome from "@/shared/components/AppChrome";

const font = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JobNest",
  description: "Generated by create next app",
  icons: {
    icon: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="%23155e75"/><svg x="8" y="8" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="%23ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="16" y="16" width="6" height="6" rx="1"/><rect x="2" y="16" width="6" height="6" rx="1"/><rect x="9" y="2" width="6" height="6" rx="1"/><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"/><path d="M12 12V8"/></svg></svg>',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${font.className} antialiased`}>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
        >
          <AuthProvider>
            <AuthModalProvider>
              <Provider>
                <AppChrome>{children}</AppChrome>
              </Provider>
            </AuthModalProvider>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}