spring:
  application:
    name: jobnest-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1-SNAPSHOT

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${spring.application.name} [%thread] %logger{36} - [%X{requestId}] %msg%n"
  level:
    root: INFO
